---
micronaut:
  application:
    name: MicronautGroovyWebConsole
  server:
    port: 8080
    baseUrl: http://localhost:8080
  views:
    thymeleaf:
      enabled: true
      character-encoding: "UTF-8"
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"

social:
  banner: "https://github.com/Joxebus/MicronautGroovyWebConsole/blob/main/img/online_groovy_console_banner.png?raw=true"

file:
  upload:
    folder: ${FILES_UPLOAD_FOLDER:/tmp/upload_folder/}  # only for local profile
    prefix: ${FILES_UPLOAD_PREFIX:/gwc-system-}         # only for dropbox and aws profiles
  cache:
    folder: ${FILES_CACHE_FOLDER:/tmp/gwc-files-cache}

